// import all export class from number.ts

import {
  Integer,
  Float,
  PositiveNumber,
  NegativeNumber,
  PositiveInteger,
  NegativeInteger,
  PositiveFloat,
  NegativeFloat,
  Zero,
  NonZero,
  NonPositive,
  NonNegative,
  NonZeroInteger,
  NonPositiveInteger,
  NonNegativeInteger,
  NonZeroFloat,
  NonPositiveFloat,
  NonNegativeFloat,
} from "./number";

export {
  Integer,
  Float,
  PositiveNumber,
  NegativeNumber,
  PositiveInteger,
  NegativeInteger,
  PositiveFloat,
  NegativeFloat,
  Zero,
  NonZero,
  NonPositive,
  NonNegative,
  NonZeroInteger,
  NonPositiveInteger,
  NonNegativeInteger,
  NonZeroFloat,
  NonPositiveFloat,
  NonNegativeFloat,
};
